version: '3.4'
services:

  http:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3001
      DB_CONN: postgres
      DB_USER: me
      DB_PASS: localpassword
      DB_NAME: tracking
    env_file:
      - ./.env.local
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: tracking
      POSTGRES_USER: me
      POSTGRES_PASSWORD: localpassword
    ports:
      - 5432
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

